import type { LocalizedText } from './LocalizedText';
import { RU_ENEMY_TEXT } from '../data/EnemyTextConfig';
import { pickLocalized } from './LocalizedText';

export type Language = 'ru' | 'en';

type Vars = Record<string, string | number>;

const STORAGE_KEY = 'rpglikedurkest-language';

const TEXT = {
    en: {
        bootTagline: 'They say a wish-granting artifact lies at the bottom. Go find it.',
        bootStart: 'Begin Expedition',
        uiVital: 'LIFE',
        eventLog: 'JOURNAL',
        hp: 'HP',
        level: 'LVL',
        xp: 'XP',
        attackShort: 'ATK',
        defenseShort: 'DEF',
        reviveShort: 'REV',
        bright: 'LIT',
        dark: 'DIM',
        goldShort: 'G',
        potionShort: 'P',
        resolveShort: 'R',
        lightShort: 'L',
        shardShort: 'S',
        depthShort: 'D',
        killShort: 'K',
        bossShort: 'B',
        prestige: 'PRESTIGE',
        depth: 'Depth',
        mapDepth: 'DEPTH',
        returnToMap: '[Space] Back to map',
        beginSilence: 'The gate closes behind you.',
        dungeonListens: 'Each room teaches the next one how to hurt you.',
        levelUp: 'Level {level} reached.',
        revive: 'Last Stand saves you. Revives left: {count}.',
        lightLower: 'The lantern loses {count} light.',
        unlocked: 'Permanent unlock: {label}.',
        chooseMove: 'Choose a move.',
        actionAttack: '[1] Strike',
        actionDefend: '[2] Guard',
        actionStagger: '[3] Break',
        actionPotion: '[{num}] Potion',
        actionCareful: '[1] Careful',
        actionForce: '[2] Force',
        actionLeave: '[3] Leave',
        actionRush: '[1] Rush',
        actionDisarm: '[2] Disarm',
        actionProbe: '[3] Study',
        actionRecover: '[1] Rest',
        actionFocus: '[2] Focus',
        actionScout: '[1] Search',
        actionSteady: '[2] Steady',
        actionPray: '[1] Pray',
        actionOffer: '[2] Offer {cost}g',
        actionRite: '[3] Rite {cost}s',
        actionDynamicLeave: '[{num}] Leave',
        actionBuyPotion: '[1] Potion {cost}g',
        actionLantern: '[{num}] Oil {cost}g',
        actionArmor: '[{num}] Armor {cost}g',
        actionRelic: '[{num}] Relic oil {cost}s',
        collectSelf: 'Catch your breath and move on.',
        intentLine: '{detail}',
        guardLine: 'Block: {guard}.',
        treasureLeaveGain: 'You leave the cache closed and recover {parts}.',
        treasureLeaveNoGain: 'You leave the cache and keep moving.',
        treasureSecured: 'You take: {parts}.',
        lockBites: 'The lock cuts your hand: {damage} damage.',
        plusXp: '+{value} XP',
        plusGold: '+{value} gold',
        plusPotion: '+1 potion',
        plusAttack: '+{value} attack',
        plusShard: '+{value} shard',
        trapRush: 'You rush through and take {damage} damage.',
        trapDisarm: 'You disarm the trap and find {gold} gold.',
        trapSnap: 'The trap snaps shut: {damage} damage.',
        trapSnapIntel: 'The trap fires before you can pull back.',
        trapProbe: 'You spend resolve and take the trap apart: {parts}.',
        restRecover: 'You rest and recover {parts}.',
        focusResolve: 'You slow your breathing and gain {value} resolve.',
        focusXp: 'You study the room and gain {value} XP.',
        shrineAttack: 'The altar marks your weapon: +1 attack this run.',
        shrineWound: 'The altar takes {damage} HP and gives {resolve} resolve.',
        shrineOffer: 'Your offering gives +{value} max HP this run.',
        shrineRite: 'The rite gives +{hp} max HP and +{resolve} resolve.',
        buyPotion: 'You buy a potion.',
        buyLantern: 'You refill the lantern: +{value} light.',
        buyArmor: 'You reinforce your armor: +{value} defense.',
        buyRelic: 'Relic oil gives +{attack} attack and +{potions} potion.',
        emptyScout: 'You search the room and find {parts}.',
        emptySteady: 'You take a moment and gain {value} resolve.',
        emptyStudy: 'You study the marks on the walls and gain {value} XP.',
        enemyFallback: 'Something steps into the light.',
        enemyInfoLocked: 'Enemy details unlock deeper down.',
        pathOpen: 'The path is clear.',
        victoryRewards: 'Reward: {parts}.',
        deathTitle: 'EXPEDITION LOST',
        deathSummary: 'Best depth: {depth}\nBosses defeated: {bosses}\nPrestige earned: +{prestige}\n{line}',
        deathRunLine: 'Depth {depth}  |  Bosses {bosses}  |  Prestige +{prestige}',
        victoryScreenTitle: 'THE ARTIFACT IS YOURS',
        victoryScreenSummary: 'You descended through {depth} layers of darkness, defeated {bosses} keepers, and claimed the Wish Artifact.\nThe dungeon has nothing left to take from you.',
        victoryNewRun: 'Descend Again',
        restart: 'Start New Run',
        reset: 'Reset soul memory',
        prestigeBank: 'Prestige bank: {value}',
        nextDiscovery: 'Next permanent unlock: {requirement} -> {label}.',
        allDiscovered: 'All permanent unlocks are open.',
        levelCard: 'Lv {level}/{max}',
        max: 'MAX',
        cost: 'Cost {cost}',
        confirmResetTitle: 'Reset all progress?',
        confirmResetBody: 'This erases prestige, permanent upgrades, and discoveries.\nThe next run starts from a clean profile.',
        confirmResetYes: 'Yes, erase all',
        cancel: 'Cancel',
        hostile: 'ENEMY',
        elite: 'ELITE',
        boss: 'BOSS',
        start: 'CAMP',
        treasure: 'CACHE',
        trap: 'TRAP',
        rest: 'REST',
        shrine: 'ALTAR',
        merchant: 'TRADER',
        empty: 'EMPTY',
        roomCamp: 'Camp',
        roomEnemy: 'Enemy',
        roomTreasure: 'Cache',
        roomTrap: 'Trap',
        roomRest: 'Rest',
        roomShrine: 'Altar',
        roomMerchant: 'Trader',
        roomElite: 'Elite',
        roomBoss: 'Boss',
        roomEmpty: 'Empty room',
        intentAttack: 'Strike',
        intentAttackDetail: 'Prepares to strike.',
        intentHeavy: 'Heavy strike',
        intentHeavyDetail: 'Raises its weapon for a heavy blow.',
        intentGuard: 'Guard',
        intentGuardDetail: 'Pulls back and covers itself.',
        intentCharge: 'Prepare',
        intentChargeDetail: 'Prepares for a stronger hit.',
        intentCurse: 'Curse',
        intentCurseDetail: 'Whispers a curse.',
        combatBoss: 'A floor keeper blocks the way.',
        combatElite: 'A stronger enemy blocks the way.',
        combatHostile: 'Enemy contact.',
        strikeCrit: 'Critical hit: {damage} damage.',
        strike: 'You deal {damage} damage.',
        brace: 'You raise your guard.',
        needResolve: 'Not enough resolve.',
        skillStagger: 'You break "{intent}" and deal {damage} damage.',
        skillLand: 'The technique deals {damage} damage.',
        noPotions: 'No potions left.',
        drinkPotion: 'You drink a potion and heal {healed} HP.',
        enemyFalls: '{name} falls.',
        planBreaks: "{name}'s move is stopped.",
        darknessCloses: 'You fall in the dark.',
        guardAbsorbs: "{name}'s block absorbs {blocked}.",
        enemyGuard: '{name} gains {guard} block.',
        enemyCharge: '{name} prepares a stronger hit.',
        enemyCurse: '{name} curses you for {damage}{suffix}.',
        curseSuffix: ' and drains {light} light',
        enemyStrikes: '{name} strikes',
        enemyHeavy: '{name} swings hard',
        enemyHits: '{label}: {damage} damage.',
        absorb: 'Your guard absorbs the hit.',
        ch_001: 'A ruler of this floor rises.',
        ch_002: 'Every system you earned is being tested at once.',
        ch_003: 'A hardened threat bars the corridor.',
        ch_004: 'Winning here should feel costly and worth it.',
        ch_005: 'Threat detected',
        ch_006: 'The corridor narrows. Something waits in the dark.',
        ch_007: 'Collect yourself and continue deeper.',
        ch_008: 'Brute: enrages when wounded.',
        ch_009: 'Stalker: may strike twice.',
        ch_010: 'Mage: charges a heavy spell.',
        ch_011: 'Boss: relentless power.',
        ch_012: 'ENRAGED!',
        ch_013: 'Charging...',
        ch_014: 'Skill: {skillCost} resolve.',
        cm_001: 'Boss encounter.',
        cm_002: 'Elite encounter.',
        cm_003: 'Hostile contact.',
        cm_004: '{name} bleeds for {bleedDamage}.',
        cm_005: 'Regen restores {healed} HP.',
        cm_006: 'You need {cost} resolve for {value}.',
        cm_007: 'Cleave lands for {dmg}.',
        cm_008: 'Bleed Strike for {dmg}. Bleed applied.',
        cm_009: 'Parry Stance breaks their rhythm.',
        cm_010: 'Parry Stance steadies you.',
        cm_011: 'Focused Strike for {dmg}. Next hit marked.',
        cm_012: 'Rupture tears for {dmg}.',
        cm_013: 'Rally restores {healed} HP and sharpens focus.',
        cm_014: 'Crushing Blow for {dmg} — the recoil bites you for 3.',
        cm_015: '{name} is stunned and skips its turn.',
        cm_016: 'You slip past {name}\'s first strike.',
        cm_017: '{name} enters a frenzy!',
        cm_018: '{name} lunges for {firstHit}.',
        cm_019: ' Double strike!',
        cm_020: '{name} channels dark energy...',
        cm_021: '{name} opens a ragged wound.',
        cm_022: '{name} saps your strength. (-1 atk 2t)',
        cm_023: '{name} hits you for {takenDamage}.{extraMessage}',
        cm_024: 'Thorns retaliate for {thorns}.',
        gs_001: 'STRESS',
        gs_002: 'Next',
        gs_003: 'VIRTUE',
        gs_004: 'AFFLICTION',
        gs_005: 'Virtue',
        gs_006: 'Affliction',
        gs_007: 'Relics: ',
        gs_008: 'Relic obtained: {value}. {value2}',
        gs_009: 'Relic obtained: {value}. {value2}',
        rf_001: 'Forgotten Cache',
        rf_002: 'A cracked chest still rewards careful hands. {value}.',
        rf_003: 'Claim the spoils and move on.',
        rf_004: 'Mechanical Snare',
        rf_005: 'A pressure plate snaps awake under your boot.',
        rf_006: 'Poison Dart Wall',
        rf_007: 'Tiny holes line the corridor. Something hisses inside.',
        rf_008: 'Collapsing Floor',
        rf_009: 'The stones shift. One wrong step and the ground gives way.',
        rf_010: 'Rush through or try to disarm it.',
        rf_011: 'The worst is behind you.',
        rf_012: 'The mechanism falls apart in your hands.',
        rf_013: 'Campfire',
        rf_014: 'The coals are low, but still warm enough to matter.',
        rf_015: 'Recover body, mind, or spirit.',
        rf_016: 'light',
        rf_017: 'The room feels less hostile for a moment.',
        rf_018: 'You leave steadier than you arrived.',
        rf_019: '[3] Meditate',
        rf_020: 'You breathe through the weight. -{meditateStressRelief} stress.',
        rf_021: 'The shadows lose an edge, if briefly.',
        rf_022: 'Mira slides a potion across without comment.',
        rf_023: 'Mira refills your lantern: +{gainedLight} light.',
        rf_024: 'Mira fastens armor straps: +{armorDefenseGain} defense.',
        rf_025: 'Mira anoints your blade. +{premiumAttackBonus} attack, +{premiumPotionBonus} potion.',
        rf_026: 'Casimir whispers a heretical line. +{prayAttackBonus} attack.',
        rf_027: 'The altar pays him in your blood. -{damage} HP, +{resolve} resolve.',
        rf_028: 'Casimir feeds the altar. +{offerMaxHpBonus} max HP this run.',
        rf_029: 'Casimir performs the wrong rite, perfectly. +{premiumMaxHpBonus} max HP, +{premiumResolveBonus} resolve.',
        rf_030: 'The Trader pays in coin instead. The deal is honoured.',
        rf_031: 'The Hollow Trader marks the ledger. The pain is precise.',
        rf_032: 'The Trader trades absence for absence. A relic settles into your kit.',
        rf_033: 'The Trader takes the potion as if it were never there. +{cost} gold.',
        rf_034: 'Veth pockets her pact and pays you in coin. "A scar is a scar."',
        rf_035: 'Veth admires the line she drew. "Carry it well."',
        rf_036: 'Veth teaches the third cut. +2 attack this run; the lesson costs.',
        rf_037: 'Veth strops your blade against the leather. +1 attack.',
        rf_038: 'The Chorister sings. -20 stress.',
        rf_039: 'The Chorister steadies your hands. +2 resolve.',
        rf_040: 'The Chorister unbinds the affliction. The song carries it away.',
        rf_041: 'There is no crack to mend today. The song becomes resolve. +3 resolve.',
        rf_042: 'Kessa pours the second cup. +4 HP, -10 stress.',
        rf_043: 'Kessa: "Third room of any depth lies. Bring two potions if you can." (+1 resolve)',
        rf_044: 'Kessa presses Sera\'s brass earring into your palm. +1 attack, +1 defense for this run.',
        rf_045: 'The shrine remembers your name.',
        rf_046: 'Forgotten Altar',
        rf_047: 'Something old still listens from beneath the stone.',
        rf_048: 'A prayer, an offering, or a careful retreat.',
        rf_049: 'The merchant counts the coins and looks away.',
        rf_050: 'The oil smells cleaner than the dungeon air.',
        rf_051: 'A fair trade, by dungeon standards.',
        rf_052: 'The merchant smiles only when relics change hands.',
        rf_053: 'Shadow Trader',
        rf_054: 'A hooded figure has already decided what your fear is worth.',
        rf_055: 'Spend carefully. This room lasts one choice.',
        rf_056: 'ENCOUNTER',
        rf_057: 'Dusty Chamber',
        rf_058: 'Stillness can hide a cache or steady a shaking hand.',
        rf_059: 'Collapsed Passage',
        rf_060: 'Rubble blocks the way, but gaps reveal hidden corners.',
        rf_061: 'Echoing Hall',
        rf_062: 'Footsteps return from walls that should not be so far away.',
        rf_063: 'Forgotten Alcove',
        rf_064: 'Someone sheltered here before. Their scratches mark the stone.',
        rf_065: 'Search the room or keep your footing.',
        rf_066: 'light',
        rf_067: 'gold',
        rf_068: 'You leave with a slightly clearer picture of the dark.',
        rf_069: 'The room gives nothing, and that helps.',
        es_001: '— Acquaintances —',
        es_002: 'Begin New Expedition',
        es_003: 'Reset soul progress',
        es_004: 'Prestige bank',
        es_005: 'Next permanent discovery',
        es_006: 'Every planned layer of permanent content has been unlocked.',
        es_007: 'MAX',
        es_008: 'Cost',
        es_009: 'Yes, delete everything',
        es_010: 'Cancel',
    },
    ru: {
        bootTagline: 'Говорят, внизу лежит артефакт, исполняющий желания. Спустись и проверь.',
        bootStart: 'Начать экспедицию',
        uiVital: 'ОЗ',
        eventLog: 'ЖУРНАЛ',
        hp: 'ОЗ',
        level: 'УР',
        xp: 'ОП',
        attackShort: 'АТК',
        defenseShort: 'ЗАЩ',
        reviveShort: 'ЖИЗН',
        bright: 'СВТ',
        dark: 'МРАК',
        goldShort: 'З',
        potionShort: 'Э',
        resolveShort: 'В',
        lightShort: 'С',
        shardShort: 'ОСК',
        depthShort: 'Г',
        killShort: 'У',
        bossShort: 'Б',
        prestige: 'ПРЕСТИЖ',
        depth: 'Глубина',
        mapDepth: 'ГЛУБИНА',
        returnToMap: '[Пробел] На карту',
        beginSilence: 'Ворота за спиной встают на засов.',
        dungeonListens: 'Каждая комната оставляет урок на камне.',
        levelUp: 'Уровень {level}.',
        revive: 'Последний шанс сработал. Зарядов: {count}.',
        lightLower: 'Фонарь гаснет на {count}.',
        unlocked: 'Память закрепила: {label}.',
        chooseMove: 'Твой ход.',
        actionAttack: '[1] Удар',
        actionDefend: '[2] Защита',
        actionStagger: '[3] Сорвать',
        actionPotion: '[{num}] Эликсир',
        actionCareful: '[1] Осторожно',
        actionForce: '[2] Вскрыть',
        actionLeave: '[3] Оставить',
        actionRush: '[1] Прорваться',
        actionDisarm: '[2] Обезвредить',
        actionProbe: '[3] Изучить',
        actionRecover: '[1] Отдохнуть',
        actionFocus: '[2] Собраться',
        actionScout: '[1] Обыскать',
        actionSteady: '[2] Выдохнуть',
        actionPray: '[1] Молиться',
        actionOffer: '[2] Подношение {cost}з',
        actionRite: '[3] Обряд {cost}о',
        actionDynamicLeave: '[{num}] Уйти',
        actionBuyPotion: '[1] Эликсир {cost}з',
        actionLantern: '[{num}] Масло {cost}з',
        actionArmor: '[{num}] Броня {cost}з',
        actionRelic: '[{num}] Реликтовое масло {cost}о',
        collectSelf: 'Выдохни и иди глубже.',
        intentLine: '{detail}',
        guardLine: 'Защита: {guard}.',
        treasureLeaveGain: 'Ты не трогаешь тайник и приходишь в себя: {parts}.',
        treasureLeaveNoGain: 'Ты оставляешь тайник и уходишь.',
        treasureSecured: 'Добыча: {parts}.',
        lockBites: 'Замок вспарывает ладонь: {damage} урона.',
        plusXp: '+{value} опыта',
        plusGold: '+{value} золота',
        plusPotion: '+1 эликсир',
        plusAttack: '+{value} атаки',
        plusShard: '+{value} осколк.',
        trapRush: 'Ты проскакиваешь ловушку: {damage} урона.',
        trapDisarm: 'Ты обезвреживаешь механизм и находишь {gold} золота.',
        trapSnap: 'Ловушка срабатывает: {damage} урона.',
        trapSnapIntel: 'Механизм щёлкает раньше, чем ты отдёргиваешь руку.',
        trapProbe: 'Ты разбираешь механизм ценой воли: {parts}.',
        restRecover: 'Короткий отдых даёт {parts}.',
        focusResolve: 'Ты ровняешь дыхание: +{value} воли.',
        focusXp: 'Ты читаешь следы в комнате: +{value} опыта.',
        shrineAttack: 'Алтарь оставляет зарубку на оружии: +1 атаки до конца забега.',
        shrineWound: 'Алтарь берёт {damage} ОЗ и возвращает {resolve} воли.',
        shrineOffer: 'Подношение укрепляет тело: +{value} макс. ОЗ до конца забега.',
        shrineRite: 'Обряд даёт +{hp} макс. ОЗ и +{resolve} воли.',
        buyPotion: 'Ты берёшь эликсир.',
        buyLantern: 'Ты доливаешь масло: +{value} света.',
        buyArmor: 'Ремни подтянуты: +{value} защиты.',
        buyRelic: 'Реликтовое масло даёт +{attack} атаки и +{potions} эликсир.',
        emptyScout: 'Ты обыскиваешь комнату: {parts}.',
        emptySteady: 'Ты берёшь паузу: +{value} воли.',
        emptyStudy: 'Ты сверяешь зарубки на стенах: +{value} опыта.',
        enemyFallback: 'Что-то входит в свет фонаря.',
        enemyInfoLocked: 'Подробности о врагах придут с опытом.',
        pathOpen: 'Путь свободен.',
        victoryRewards: 'Награда: {parts}.',
        deathTitle: 'ЭКСПЕДИЦИЯ НЕ ВЕРНУЛАСЬ',
        deathSummary: 'Лучшая глубина: {depth}\nБоссов побеждено: {bosses}\nПрестиж: +{prestige}\n{line}',
        deathRunLine: 'Глубина {depth}  |  Боссы {bosses}  |  Престиж +{prestige}',
        victoryScreenTitle: 'АРТЕФАКТ У ТЕБЯ',
        victoryScreenSummary: 'Ты прошёл {depth} глубин, победил {bosses} хранителей и вынес Артефакт Желаний.\nВнизу больше нечего у тебя забрать.',
        victoryNewRun: 'Спуститься снова',
        restart: 'Новый забег',
        reset: 'Стереть память',
        prestigeBank: 'Запас престижа: {value}',
        nextDiscovery: 'Следующее открытие: {requirement} -> {label}.',
        allDiscovered: 'Все постоянные открытия уже закреплены.',
        levelCard: 'Ур {level}/{max}',
        max: 'МАКС',
        cost: 'Цена {cost}',
        confirmResetTitle: 'Стереть весь прогресс?',
        confirmResetBody: 'Это сотрёт престиж, улучшения и открытия.\nСледующий забег начнётся с чистого профиля.',
        confirmResetYes: 'Да, стереть всё',
        cancel: 'Отмена',
        hostile: 'ВРАГ',
        elite: 'ЭЛИТА',
        boss: 'БОСС',
        start: 'ЛАГЕРЬ',
        treasure: 'ТАЙНИК',
        trap: 'ЛОВУШКА',
        rest: 'ПРИВАЛ',
        shrine: 'АЛТАРЬ',
        merchant: 'ТОРГОВЕЦ',
        empty: 'ПУСТАЯ',
        roomCamp: 'Лагерь',
        roomEnemy: 'Враг',
        roomTreasure: 'Тайник',
        roomTrap: 'Ловушка',
        roomRest: 'Привал',
        roomShrine: 'Алтарь',
        roomMerchant: 'Торговец',
        roomElite: 'Элита',
        roomBoss: 'Босс',
        roomEmpty: 'Пустая комната',
        intentAttack: 'Удар',
        intentAttackDetail: 'Собирается ударить.',
        intentHeavy: 'Сильный удар',
        intentHeavyDetail: 'Поднимает оружие для тяжёлого удара.',
        intentGuard: 'Защита',
        intentGuardDetail: 'Отходит и закрывается.',
        intentCharge: 'Подготовка',
        intentChargeDetail: 'Копит силу для следующего удара.',
        intentCurse: 'Проклятие',
        intentCurseDetail: 'Шепчет сквозь зубы.',
        combatBoss: 'Хранитель перекрыл лестницу вниз.',
        combatElite: 'Опытный враг держит проход.',
        combatHostile: 'Контакт с врагом.',
        strikeCrit: 'Критический удар: {damage} урона.',
        strike: 'Ты наносишь {damage} урона.',
        brace: 'Ты встаёшь в защиту.',
        needResolve: 'Не хватает воли.',
        skillStagger: 'Ты срываешь "{intent}" и наносишь {damage} урона.',
        skillLand: 'Приём наносит {damage} урона.',
        noPotions: 'Эликсиров нет.',
        drinkPotion: 'Ты пьёшь эликсир: +{healed} ОЗ.',
        enemyFalls: '{name} падает.',
        planBreaks: 'Действие {name} сорвано.',
        darknessCloses: 'Свет гаснет. Ты падаешь.',
        guardAbsorbs: 'Защита {name} поглощает {blocked}.',
        enemyGuard: '{name} получает {guard} защиты.',
        enemyCharge: '{name} копит силу для удара.',
        enemyCurse: '{name} проклинает тебя: {damage}{suffix}.',
        curseSuffix: ' и гасит {light} света',
        enemyStrikes: '{name} бьёт',
        enemyHeavy: '{name} бьёт со всей силы',
        enemyHits: '{label}: {damage} урона.',
        absorb: 'Твоя защита держит удар.',
        ch_001: 'Хранитель этажа перекрывает лестницу.',
        ch_002: 'Сейчас пригодится всё, чему тебя научил спуск.',
        ch_003: 'Опытный враг держит коридор.',
        ch_004: 'Победа здесь будет дорогой. Добыча тоже.',
        ch_005: 'Контакт',
        ch_006: 'Коридор сужается. Впереди заняли проход.',
        ch_007: 'Выдохни и иди глубже.',
        ch_008: 'Громила: ярится в ране.',
        ch_009: 'Охотник: бьёт сериями.',
        ch_010: 'Маг: копит силу для тяжёлого удара.',
        ch_011: 'Босс: держит путь вниз.',
        ch_012: 'ЯРОСТЬ!',
        ch_013: 'Копит силу...',
        ch_014: 'Навык: {skillCost} воли.',
        cm_001: 'Босс держит проход.',
        cm_002: 'Элитный враг.',
        cm_003: 'Контакт с врагом.',
        cm_004: '{name} теряет от кровотечения {bleedDamage}.',
        cm_005: 'Регенерация возвращает {healed} ОЗ.',
        cm_006: 'Нужно {cost} воли для навыка "{value}".',
        cm_007: 'Рубящий удар: {dmg}.',
        cm_008: 'Кровопускание: {dmg}. Кровотечение наложено.',
        cm_009: 'Парирование сбивает ритм врага.',
        cm_010: 'Парирование выравнивает твою стойку.',
        cm_011: 'Точный удар: {dmg}. Метка поставлена.',
        cm_012: 'Разрыв: {dmg}.',
        cm_013: 'Адреналин возвращает {healed} ОЗ и собирает фокус.',
        cm_014: 'Сокрушающий удар: {dmg}; отдача бьёт тебя на 3.',
        cm_015: '{name} оглушён и пропускает ход.',
        cm_016: 'Ты уходишь от первого удара {name}.',
        cm_017: '{name} срывается в ярость!',
        cm_018: '{name} бросается вперёд: {firstHit}.',
        cm_019: ' Второй удар!',
        cm_020: '{name} копит силу...',
        cm_021: '{name} раскрывает рваную рану.',
        cm_022: '{name} вытягивает силы. (-1 атака на 2 хода)',
        cm_023: '{name} попадает по тебе: {takenDamage}.{extraMessage}',
        cm_024: 'Шипы отвечают: {thorns}.',
        gs_001: 'СТРЕСС',
        gs_002: 'Дальше',
        gs_003: 'ДОБЛЕСТЬ',
        gs_004: 'СРЫВ',
        gs_005: 'Доблесть',
        gs_006: 'Срыв',
        gs_007: 'Реликвии: ',
        gs_008: 'Реликвия: {value}. {value2}',
        gs_009: 'Реликвия: {value}. {value2}',
        rf_001: 'Старый тайник',
        rf_002: 'Треснувший сундук не любит спешки. {value}.',
        rf_003: 'Забери добычу и уходи.',
        rf_004: 'Проволочная петля',
        rf_005: 'Плита щёлкает под сапогом.',
        rf_006: 'Дротиковая стена',
        rf_007: 'В камне ряд мелких отверстий. Внутри шипит давление.',
        rf_008: 'Просевший пол',
        rf_009: 'Камни ходят под ногами. Вес решит всё.',
        rf_010: 'Проскочить или разобрать механизм.',
        rf_011: 'Механизм замолк.',
        rf_012: 'Пружина сдаётся у тебя в руках.',
        rf_013: 'Костёр',
        rf_014: 'Угли уже слабые, но тепла в них ещё хватает.',
        rf_015: 'Залатай тело, дыхание или нервы.',
        rf_016: 'света',
        rf_017: 'Комната на минуту отпускает.',
        rf_018: 'Ты уходишь ровнее, чем вошёл.',
        rf_019: '[3] Медитация',
        rf_020: 'Ты выдыхаешь лишний вес. -{meditateStressRelief} стресса.',
        rf_021: 'Углы на миг теряют зубы.',
        rf_022: 'Мира без слов ставит эликсир ближе.',
        rf_023: 'Мира доливает масло в фонарь: +{gainedLight} света.',
        rf_024: 'Мира затягивает ремни брони: +{armorDefenseGain} защиты.',
        rf_025: 'Мира смазывает клинок реликтовым маслом. +{premiumAttackBonus} атаки, +{premiumPotionBonus} эликсир.',
        rf_026: 'Казимир шепчет строку безымянной молитвы. +{prayAttackBonus} атаки.',
        rf_027: 'Алтарь берёт кровь и возвращает волю. -{damage} ОЗ, +{resolve} воли.',
        rf_028: 'Казимир кладёт подношение на камень. +{offerMaxHpBonus} к макс. ОЗ на этот забег.',
        rf_029: 'Казимир проводит обряд слишком уверенно. +{premiumMaxHpBonus} макс. ОЗ, +{premiumResolveBonus} воли.',
        rf_030: 'Торговец платит монетой. Сделка закрыта.',
        rf_031: 'Полый торговец ставит отметку в книге. Боль точна.',
        rf_032: 'Торговец забирает часть тебя. Реликвия ложится в сумку.',
        rf_033: 'Торговец забирает эликсир так, будто он уже был его. +{cost} золота.',
        rf_034: 'Вет прячет договор и платит монетой. "Шрам есть шрам."',
        rf_035: 'Вет смотрит на свежую линию. "Неси её достойно."',
        rf_036: 'Вет показывает третий разрез: +2 атаки на этот забег. Цена остаётся с тобой.',
        rf_037: 'Вет правит клинок о старую кожу. +1 атаки.',
        rf_038: 'Хорист держит низкую ноту. -20 стресса.',
        rf_039: 'Хорист выравнивает твои руки. +2 воли.',
        rf_040: 'Хорист ослабляет срыв. Песня держит трещину закрытой.',
        rf_041: 'Сегодня нечего чинить. Песня становится волей. +3 воли.',
        rf_042: 'Кесса наливает вторую кружку. +4 ОЗ, -10 стресса.',
        rf_043: 'Кесса: "Третья комната на любой глубине врёт. Держи второй эликсир, если можешь." (+1 воля)',
        rf_044: 'Кесса вкладывает в ладонь латунную серьгу Серы. +1 атаки и +1 защиты на этот забег.',
        rf_045: 'Алтарь запомнил твою кровь.',
        rf_046: 'Старый алтарь',
        rf_047: 'Под камнем что-то слушает сквозь пыль.',
        rf_048: 'Молитва, подношение или тихий уход.',
        rf_049: 'Торговец считает монеты, не поднимая глаз.',
        rf_050: 'Масло пахнет чище здешнего воздуха.',
        rf_051: 'Честная сделка. Насколько здесь бывает.',
        rf_052: 'Торговец улыбается, когда реликвия меняет хозяина.',
        rf_053: 'Торговец в капюшоне',
        rf_054: 'Фигура в капюшоне уже оценила твой страх.',
        rf_055: 'Выбирай осторожно. Здесь дают одну сделку.',
        rf_056: 'ВСТРЕЧА',
        rf_057: 'Пыльная камера',
        rf_058: 'В тишине слышно и тайник, и собственные руки.',
        rf_059: 'Заваленный проход',
        rf_060: 'Завал держит проход, но в щелях видны боковые ниши.',
        rf_061: 'Гулкий зал',
        rf_062: 'Шаги возвращаются позднее, чем должны.',
        rf_063: 'Старая ниша',
        rf_064: 'Здесь уже прятались. Царапины на камне ещё светлые.',
        rf_065: 'Обыскать комнату или выровнять дыхание.',
        rf_066: 'света',
        rf_067: 'золота',
        rf_068: 'Ты уходишь с более ясной картой углов.',
        rf_069: 'Комната ничего не требует. Этого достаточно.',
        es_001: '— Встреченные —',
        es_002: 'Новый забег',
        es_003: 'Стереть память',
        es_004: 'Запас престижа',
        es_005: 'Следующее открытие',
        es_006: 'Все постоянные открытия уже закреплены.',
        es_007: 'МАКС',
        es_008: 'Цена',
        es_009: 'Да, удалить всё',
        es_010: 'Отмена',
    },
} as const;

export class Localization {
    language: Language;

    constructor(language: Language = getSavedLanguage()) {
        this.language = language;
    }

    t(key: keyof typeof TEXT.en, vars: Vars = {}): string {
        const template: string = TEXT[this.language][key] || TEXT.en[key];
        return Object.entries(vars).reduce(
            (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
            template
        );
    }

    pick(text: LocalizedText | string | null | undefined): string {
        return pickLocalized(this.language, text);
    }

    format(text: LocalizedText | string | null | undefined, vars: Vars = {}): string {
        const template = this.pick(text);
        return Object.entries(vars).reduce(
            (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
            template
        );
    }

    enemyName(name: string): string {
        return this.language === 'ru' ? RU_ENEMY_TEXT[name]?.name ?? name : name;
    }

    enemyDescription(name: string, fallback: string): string {
        return this.language === 'ru' ? RU_ENEMY_TEXT[name]?.description ?? fallback : fallback;
    }

    toggle(): Language {
        const next = this.language === 'ru' ? 'en' : 'ru';
        this.language = next;
        saveLanguage(next);
        return next;
    }
}

export function getSavedLanguage(): Language {
    try {
        return window.localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'ru';
    } catch {
        return 'ru';
    }
}

export function saveLanguage(language: Language): void {
    try {
        window.localStorage.setItem(STORAGE_KEY, language);
    } catch {
        // Language still applies for the current restart path.
    }
    if (typeof document !== 'undefined') {
        document.documentElement.lang = language;
    }
}
