import type { LocalizedText } from './LocalizedText';
import { RU_ENEMY_TEXT } from '../data/EnemyTextConfig';
import { pickLocalized } from './LocalizedText';

export type Language = 'ru' | 'en';

type Vars = Record<string, string | number>;

const STORAGE_KEY = 'rpglikedurkest-language';

const TEXT = {
    en: {
        bootTagline: 'They say a wish-granting artifact lies at the bottom. Go find it.',
        bootStart: 'Begin Expedition',
        uiVital: 'LIFE',
        eventLog: 'JOURNAL',
        hp: 'HP',
        level: 'LVL',
        xp: 'XP',
        attackShort: 'ATK',
        defenseShort: 'DEF',
        reviveShort: 'REV',
        bright: 'LIT',
        dark: 'DIM',
        goldShort: 'G',
        potionShort: 'P',
        resolveShort: 'R',
        lightShort: 'L',
        shardShort: 'S',
        depthShort: 'D',
        killShort: 'K',
        bossShort: 'B',
        prestige: 'PRESTIGE',
        depth: 'Depth',
        mapDepth: 'DEPTH',
        returnToMap: '[Space] Back to map',
        beginSilence: 'The gate closes behind you.',
        dungeonListens: 'Each room teaches the next one how to hurt you.',
        levelUp: 'Level {level} reached.',
        revive: 'Last Stand saves you. Revives left: {count}.',
        lightLower: 'The lantern loses {count} light.',
        unlocked: 'Permanent unlock: {label}.',
        chooseMove: 'Choose a move.',
        actionAttack: '[1] Strike',
        actionDefend: '[2] Guard',
        actionStagger: '[3] Break',
        actionPotion: '[{num}] Potion',
        actionCareful: '[1] Careful',
        actionForce: '[2] Force',
        actionLeave: '[3] Leave',
        actionRush: '[1] Rush',
        actionDisarm: '[2] Disarm',
        actionProbe: '[3] Study',
        actionRecover: '[1] Rest',
        actionFocus: '[2] Focus',
        actionScout: '[1] Search',
        actionSteady: '[2] Steady',
        actionPray: '[1] Pray',
        actionOffer: '[2] Offer {cost}g',
        actionRite: '[3] Rite {cost}s',
        actionDynamicLeave: '[{num}] Leave',
        actionBuyPotion: '[1] Potion {cost}g',
        actionLantern: '[{num}] Oil {cost}g',
        actionArmor: '[{num}] Armor {cost}g',
        actionRelic: '[{num}] Relic oil {cost}s',
        collectSelf: 'Catch your breath and move on.',
        intentLine: '{detail}',
        guardLine: 'Block: {guard}.',
        treasureLeaveGain: 'You leave the cache closed and recover {parts}.',
        treasureLeaveNoGain: 'You leave the cache and keep moving.',
        treasureSecured: 'You take: {parts}.',
        lockBites: 'The lock cuts your hand: {damage} damage.',
        plusXp: '+{value} XP',
        plusGold: '+{value} gold',
        plusPotion: '+1 potion',
        plusAttack: '+{value} attack',
        plusShard: '+{value} shard',
        trapRush: 'You rush through and take {damage} damage.',
        trapDisarm: 'You disarm the trap and find {gold} gold.',
        trapSnap: 'The trap snaps shut: {damage} damage.',
        trapSnapIntel: 'The trap fires before you can pull back.',
        trapProbe: 'You spend resolve and take the trap apart: {parts}.',
        restRecover: 'You rest and recover {parts}.',
        focusResolve: 'You slow your breathing and gain {value} resolve.',
        focusXp: 'You study the room and gain {value} XP.',
        shrineAttack: 'The altar marks your weapon: +1 attack this run.',
        shrineWound: 'The altar takes {damage} HP and gives {resolve} resolve.',
        shrineOffer: 'Your offering gives +{value} max HP this run.',
        shrineRite: 'The rite gives +{hp} max HP and +{resolve} resolve.',
        buyPotion: 'You buy a potion.',
        buyLantern: 'You refill the lantern: +{value} light.',
        buyArmor: 'You reinforce your armor: +{value} defense.',
        buyRelic: 'Relic oil gives +{attack} attack and +{potions} potion.',
        emptyScout: 'You search the room and find {parts}.',
        emptySteady: 'You take a moment and gain {value} resolve.',
        emptyStudy: 'You study the marks on the walls and gain {value} XP.',
        enemyFallback: 'Something steps into the light.',
        enemyInfoLocked: 'Enemy details unlock deeper down.',
        pathOpen: 'The path is clear.',
        victoryRewards: 'Reward: {parts}.',
        deathTitle: 'EXPEDITION LOST',
        deathSummary: 'Best depth: {depth}\nBosses defeated: {bosses}\nPrestige earned: +{prestige}\n{line}',
        deathRunLine: 'Depth {depth}  |  Bosses {bosses}  |  Prestige +{prestige}',
        victoryScreenTitle: 'THE ARTIFACT IS YOURS',
        victoryScreenSummary: 'You descended through {depth} layers of darkness, defeated {bosses} keepers, and claimed the Wish Artifact.\nThe dungeon has nothing left to take from you.',
        victoryNewRun: 'Descend Again',
        restart: 'Start New Run',
        reset: 'Reset soul memory',
        prestigeBank: 'Prestige bank: {value}',
        nextDiscovery: 'Next permanent unlock: {requirement} -> {label}.',
        allDiscovered: 'All permanent unlocks are open.',
        levelCard: 'Lv {level}/{max}',
        max: 'MAX',
        cost: 'Cost {cost}',
        confirmResetTitle: 'Reset all progress?',
        confirmResetBody: 'This erases prestige, permanent upgrades, and discoveries.\nThe next run starts from a clean profile.',
        confirmResetYes: 'Yes, erase all',
        cancel: 'Cancel',
        hostile: 'ENEMY',
        elite: 'ELITE',
        boss: 'BOSS',
        start: 'CAMP',
        treasure: 'CACHE',
        trap: 'TRAP',
        rest: 'REST',
        shrine: 'ALTAR',
        merchant: 'TRADER',
        empty: 'EMPTY',
        roomCamp: 'Camp',
        roomEnemy: 'Enemy',
        roomTreasure: 'Cache',
        roomTrap: 'Trap',
        roomRest: 'Rest',
        roomShrine: 'Altar',
        roomMerchant: 'Trader',
        roomElite: 'Elite',
        roomBoss: 'Boss',
        roomEmpty: 'Empty room',
        intentAttack: 'Strike',
        intentAttackDetail: 'Prepares to strike.',
        intentHeavy: 'Heavy strike',
        intentHeavyDetail: 'Raises its weapon for a heavy blow.',
        intentGuard: 'Guard',
        intentGuardDetail: 'Pulls back and covers itself.',
        intentCharge: 'Prepare',
        intentChargeDetail: 'Prepares for a stronger hit.',
        intentCurse: 'Curse',
        intentCurseDetail: 'Whispers a curse.',
        combatBoss: 'A floor keeper blocks the way.',
        combatElite: 'A stronger enemy blocks the way.',
        combatHostile: 'Enemy contact.',
        strikeCrit: 'Critical hit: {damage} damage.',
        strike: 'You deal {damage} damage.',
        brace: 'You raise your guard.',
        needResolve: 'Not enough resolve.',
        skillStagger: 'You break "{intent}" and deal {damage} damage.',
        skillLand: 'The technique deals {damage} damage.',
        noPotions: 'No potions left.',
        drinkPotion: 'You drink a potion and heal {healed} HP.',
        enemyFalls: '{name} falls.',
        planBreaks: "{name}'s move is stopped.",
        darknessCloses: 'You fall in the dark.',
        guardAbsorbs: "{name}'s block absorbs {blocked}.",
        enemyGuard: '{name} gains {guard} block.',
        enemyCharge: '{name} prepares a stronger hit.',
        enemyCurse: '{name} curses you for {damage}{suffix}.',
        curseSuffix: ' and drains {light} light',
        enemyStrikes: '{name} strikes',
        enemyHeavy: '{name} swings hard',
        enemyHits: '{label}: {damage} damage.',
        absorb: 'Your guard absorbs the hit.',
    },
    ru: {
        bootTagline: 'Говорят, внизу лежит артефакт, исполняющий желания. Спустись и проверь.',
        bootStart: 'Начать экспедицию',
        uiVital: 'ОЗ',
        eventLog: 'ЖУРНАЛ',
        hp: 'ОЗ',
        level: 'УР',
        xp: 'ОП',
        attackShort: 'АТК',
        defenseShort: 'ЗАЩ',
        reviveShort: 'ЖИЗН',
        bright: 'СВТ',
        dark: 'МРАК',
        goldShort: 'З',
        potionShort: 'Э',
        resolveShort: 'В',
        lightShort: 'С',
        shardShort: 'ОСК',
        depthShort: 'Г',
        killShort: 'У',
        bossShort: 'Б',
        prestige: 'ПРЕСТИЖ',
        depth: 'Глубина',
        mapDepth: 'ГЛУБИНА',
        returnToMap: '[Пробел] На карту',
        beginSilence: 'Ворота за спиной встают на засов.',
        dungeonListens: 'Каждая комната оставляет урок на камне.',
        levelUp: 'Уровень {level}.',
        revive: 'Последний шанс сработал. Зарядов: {count}.',
        lightLower: 'Фонарь гаснет на {count}.',
        unlocked: 'Память закрепила: {label}.',
        chooseMove: 'Твой ход.',
        actionAttack: '[1] Удар',
        actionDefend: '[2] Защита',
        actionStagger: '[3] Сорвать',
        actionPotion: '[{num}] Эликсир',
        actionCareful: '[1] Осторожно',
        actionForce: '[2] Вскрыть',
        actionLeave: '[3] Оставить',
        actionRush: '[1] Прорваться',
        actionDisarm: '[2] Обезвредить',
        actionProbe: '[3] Изучить',
        actionRecover: '[1] Отдохнуть',
        actionFocus: '[2] Собраться',
        actionScout: '[1] Обыскать',
        actionSteady: '[2] Выдохнуть',
        actionPray: '[1] Молиться',
        actionOffer: '[2] Подношение {cost}з',
        actionRite: '[3] Обряд {cost}о',
        actionDynamicLeave: '[{num}] Уйти',
        actionBuyPotion: '[1] Эликсир {cost}з',
        actionLantern: '[{num}] Масло {cost}з',
        actionArmor: '[{num}] Броня {cost}з',
        actionRelic: '[{num}] Реликтовое масло {cost}о',
        collectSelf: 'Выдохни и иди глубже.',
        intentLine: '{detail}',
        guardLine: 'Защита: {guard}.',
        treasureLeaveGain: 'Ты не трогаешь тайник и приходишь в себя: {parts}.',
        treasureLeaveNoGain: 'Ты оставляешь тайник и уходишь.',
        treasureSecured: 'Добыча: {parts}.',
        lockBites: 'Замок вспарывает ладонь: {damage} урона.',
        plusXp: '+{value} опыта',
        plusGold: '+{value} золота',
        plusPotion: '+1 эликсир',
        plusAttack: '+{value} атаки',
        plusShard: '+{value} осколк.',
        trapRush: 'Ты проскакиваешь ловушку: {damage} урона.',
        trapDisarm: 'Ты обезвреживаешь механизм и находишь {gold} золота.',
        trapSnap: 'Ловушка срабатывает: {damage} урона.',
        trapSnapIntel: 'Механизм щёлкает раньше, чем ты отдёргиваешь руку.',
        trapProbe: 'Ты разбираешь механизм ценой воли: {parts}.',
        restRecover: 'Короткий отдых даёт {parts}.',
        focusResolve: 'Ты ровняешь дыхание: +{value} воли.',
        focusXp: 'Ты читаешь следы в комнате: +{value} опыта.',
        shrineAttack: 'Алтарь оставляет зарубку на оружии: +1 атаки до конца забега.',
        shrineWound: 'Алтарь берёт {damage} ОЗ и возвращает {resolve} воли.',
        shrineOffer: 'Подношение укрепляет тело: +{value} макс. ОЗ до конца забега.',
        shrineRite: 'Обряд даёт +{hp} макс. ОЗ и +{resolve} воли.',
        buyPotion: 'Ты берёшь эликсир.',
        buyLantern: 'Ты доливаешь масло: +{value} света.',
        buyArmor: 'Ремни подтянуты: +{value} защиты.',
        buyRelic: 'Реликтовое масло даёт +{attack} атаки и +{potions} эликсир.',
        emptyScout: 'Ты обыскиваешь комнату: {parts}.',
        emptySteady: 'Ты берёшь паузу: +{value} воли.',
        emptyStudy: 'Ты сверяешь зарубки на стенах: +{value} опыта.',
        enemyFallback: 'Что-то входит в свет фонаря.',
        enemyInfoLocked: 'Подробности о врагах придут с опытом.',
        pathOpen: 'Путь свободен.',
        victoryRewards: 'Награда: {parts}.',
        deathTitle: 'ЭКСПЕДИЦИЯ НЕ ВЕРНУЛАСЬ',
        deathSummary: 'Лучшая глубина: {depth}\nБоссов побеждено: {bosses}\nПрестиж: +{prestige}\n{line}',
        deathRunLine: 'Глубина {depth}  |  Боссы {bosses}  |  Престиж +{prestige}',
        victoryScreenTitle: 'АРТЕФАКТ У ТЕБЯ',
        victoryScreenSummary: 'Ты прошёл {depth} глубин, победил {bosses} хранителей и вынес Артефакт Желаний.\nВнизу больше нечего у тебя забрать.',
        victoryNewRun: 'Спуститься снова',
        restart: 'Новый забег',
        reset: 'Стереть память',
        prestigeBank: 'Запас престижа: {value}',
        nextDiscovery: 'Следующее открытие: {requirement} -> {label}.',
        allDiscovered: 'Все постоянные открытия уже закреплены.',
        levelCard: 'Ур {level}/{max}',
        max: 'МАКС',
        cost: 'Цена {cost}',
        confirmResetTitle: 'Стереть весь прогресс?',
        confirmResetBody: 'Это сотрёт престиж, улучшения и открытия.\nСледующий забег начнётся с чистого профиля.',
        confirmResetYes: 'Да, стереть всё',
        cancel: 'Отмена',
        hostile: 'ВРАГ',
        elite: 'ЭЛИТА',
        boss: 'БОСС',
        start: 'ЛАГЕРЬ',
        treasure: 'ТАЙНИК',
        trap: 'ЛОВУШКА',
        rest: 'ПРИВАЛ',
        shrine: 'АЛТАРЬ',
        merchant: 'ТОРГОВЕЦ',
        empty: 'ПУСТАЯ',
        roomCamp: 'Лагерь',
        roomEnemy: 'Враг',
        roomTreasure: 'Тайник',
        roomTrap: 'Ловушка',
        roomRest: 'Привал',
        roomShrine: 'Алтарь',
        roomMerchant: 'Торговец',
        roomElite: 'Элита',
        roomBoss: 'Босс',
        roomEmpty: 'Пустая комната',
        intentAttack: 'Удар',
        intentAttackDetail: 'Собирается ударить.',
        intentHeavy: 'Сильный удар',
        intentHeavyDetail: 'Поднимает оружие для тяжёлого удара.',
        intentGuard: 'Защита',
        intentGuardDetail: 'Отходит и закрывается.',
        intentCharge: 'Подготовка',
        intentChargeDetail: 'Копит силу для следующего удара.',
        intentCurse: 'Проклятие',
        intentCurseDetail: 'Шепчет сквозь зубы.',
        combatBoss: 'Хранитель перекрыл лестницу вниз.',
        combatElite: 'Опытный враг держит проход.',
        combatHostile: 'Контакт с врагом.',
        strikeCrit: 'Критический удар: {damage} урона.',
        strike: 'Ты наносишь {damage} урона.',
        brace: 'Ты встаёшь в защиту.',
        needResolve: 'Не хватает воли.',
        skillStagger: 'Ты срываешь "{intent}" и наносишь {damage} урона.',
        skillLand: 'Приём наносит {damage} урона.',
        noPotions: 'Эликсиров нет.',
        drinkPotion: 'Ты пьёшь эликсир: +{healed} ОЗ.',
        enemyFalls: '{name} падает.',
        planBreaks: 'Действие {name} сорвано.',
        darknessCloses: 'Свет гаснет. Ты падаешь.',
        guardAbsorbs: 'Защита {name} поглощает {blocked}.',
        enemyGuard: '{name} получает {guard} защиты.',
        enemyCharge: '{name} копит силу для удара.',
        enemyCurse: '{name} проклинает тебя: {damage}{suffix}.',
        curseSuffix: ' и гасит {light} света',
        enemyStrikes: '{name} бьёт',
        enemyHeavy: '{name} бьёт со всей силы',
        enemyHits: '{label}: {damage} урона.',
        absorb: 'Твоя защита держит удар.',
    },
} as const;

export class Localization {
    language: Language;

    constructor(language: Language = getSavedLanguage()) {
        this.language = language;
    }

    t(key: keyof typeof TEXT.en, vars: Vars = {}): string {
        const template: string = TEXT[this.language][key] || TEXT.en[key];
        return Object.entries(vars).reduce(
            (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
            template
        );
    }

    pick(text: LocalizedText | string | null | undefined): string {
        return pickLocalized(this.language, text);
    }

    format(text: LocalizedText | string | null | undefined, vars: Vars = {}): string {
        const template = this.pick(text);
        return Object.entries(vars).reduce(
            (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
            template
        );
    }

    enemyName(name: string): string {
        return this.language === 'ru' ? RU_ENEMY_TEXT[name]?.name ?? name : name;
    }

    enemyDescription(name: string, fallback: string): string {
        return this.language === 'ru' ? RU_ENEMY_TEXT[name]?.description ?? fallback : fallback;
    }

    toggle(): Language {
        const next = this.language === 'ru' ? 'en' : 'ru';
        this.language = next;
        saveLanguage(next);
        return next;
    }
}

export function getSavedLanguage(): Language {
    try {
        return window.localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'ru';
    } catch {
        return 'ru';
    }
}

export function saveLanguage(language: Language): void {
    try {
        window.localStorage.setItem(STORAGE_KEY, language);
    } catch {
        // Language still applies for the current restart path.
    }
    if (typeof document !== 'undefined') {
        document.documentElement.lang = language;
    }
}
